baseURL = 'https://fqdeng.com'
languageCode = 'en-us'
title = "My Blog"
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'fqdeng9'               # twitter.com/YOUR_TWITTER_ID
  github = 'fqdeng'                 # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  #linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  #mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  #threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/21285645?v=4'                 # gravatar email or image url
  name = 'fqdeng'
  bio = 'winters'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  comments = false
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'header.png'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
[params.giscus]
  repo = 'fqdeng/website'                 # see https://giscus.app for more details
  repoId = 'R_kgDOMcl9uQ'
  category = 'Announcements'
  categoryId = 'DIC_kwDOMcl9uc4ChQWI'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'


